### ISSUE TITLE
Start ballista ui with docker, but it can not found ballista scheduler

### ISSUE THREAD

**Issue by gaojun2048** [apache/arrow-datafusion#1389]
**Describe the bug**
Start ballista ui with docker, but it can not found ballista scheduler

**To Reproduce**
I clone the core from master branch. And then use `./dev/build-ballista-docker.sh` and `./dev/build-ui.sh` finished the docker image build.
I start the image with a docker-compose.yaml , it`s the content:

```
version: "2.2"
services:
  ballista-scheduler:
    image: ballista:0.6.0
    command: "/scheduler  --bind-host 0.0.0.0 --bind-port 50050"
    ports:
      - "50050:50050"
    environment:
      - RUST_LOG=info
    volumes:
      - ./data1:/data1
  ballista-executor:
    image: ballista:0.6.0
    command: "/executor --bind-host 0.0.0.0 --bind-port 50051 --scheduler-host ballista-scheduler"
    ports:
      - "50051:50051"
    environment:
      - RUST_LOG=info
    volumes:
      - ./data1:/data1
    depends_on:
      - ballista-scheduler

  ballista-scheduler-ui:
    image: ballista-scheduler-ui:0.6.0
    ports:
      - "4000:80"
    environment:
      - RUST_LOG=debug
    volumes:
      - ./data1:/data1
    depends_on:
      - ballista-scheduler
```

The docker container is start success. But can not find scheduler in the ui.

![image](https://user-images.githubusercontent.com/32193458/144351652-f4a27487-bf51-4310-83e4-d1cc68f5f595.png)

**Expected behavior**

**Additional context**
