### ISSUE TITLE
Improve formatting of logical plans containing subquery expressions

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#2898]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
When we implemented subqueries in the logical plan, we did not update the display logic, and the plans are hard to read because the indentation is not correct.

**Describe the solution you'd like**
Fix the formatting. Here is a proposal:

```
Projection: #employee_csv.id
  Filter: #employee_csv.state IN (<subquery>)
    Subquery:
      TableScan: employee_csv projection=[state]
    TableScan: employee_csv projection=[id, state]
```

**Describe alternatives you've considered**
None

**Additional context**
None
