### ISSUE TITLE
Eliminate SubqueryAlias

### ISSUE THREAD

**Issue by jackwener** [apache/arrow-datafusion#5407]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Eliminate SubqueryAlias by using a rule.

like Spark have a rule `EliminateSubqueryAlias`.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jackwener** [comment]
cc @mingmwang

**Comment by jackwener** [comment]
I have tried to do this rule, but failed.

If anyone is interested in it, feel free @me assign to you,

**Comment by Jefffrey** [comment]
Could you provide some more details/your thinking for this @jackwener ?

I assume the intention is for this to be an rule during logical plan optimization (at the end?) to remove the SubqueryAlias nodes and for nodes higher above the original SubqueryAlias node to have any references to the SubqueryAlias to be expanded to a proper qualified reference like so from:

```
Projection: a.a
  SubqueryAlias: a
    Filter: ta.a = Int64(1)
      TableScan: ta projection=[a]
```

to:

```
Projection: ta.a
  Filter: ta.a = Int64(1)
    TableScan: ta projection=[a]
```

Does this line up with what you're imagining?

**Comment by jackwener** [comment]
> I assume the intention is for this to be an rule during logical plan optimization (at the end?) 
We can remove it at a relatively early stage, so plan can be optimized by `PushdownProjection` `EliminateProjection` again.

I think a **possible** method : we can use alias to **keep schema unchanged** like following

```
Projection: t1.a
  SubqueryAlias: t1
    Filter: ta.a = Int64(1)
      TableScan: ta projection=[a]
to:
Projection: ta.a as t1.a
  Filter: ta.a = Int64(1)
    TableScan: ta projection=[a]
```
