### ISSUE TITLE
Why hashing benefits from partitioning? 

### ISSUE THREAD

**Issue by YjyJeff** [apache/arrow-datafusion#7834]
### Describe the bug

The [comment](https://github.com/apache/arrow-datafusion/blob/main/datafusion/core/src/physical_optimizer/enforce_distribution.rs#L1047) in `EnforeDistribution` said:

> Hashing benefits from partitioning, add a round-robin repartition before it

It sounds pretty odd. In a specific example:
```
before: 

AggregateExec: mode=FinalPartitioned, gby=[ip@0 as ip], aggr=[COUNT(Int64(1))]
  AggregateExec: mode=Partial, gby=[ip@0 as ip], aggr=[COUNT(Int64(1))]

after:

AggregateExec: mode=FinalPartitioned, gby=[ip@0 as ip], aggr=[COUNT(Int64(1))]
  RepartitionExec: partitioning=Hash([ip@0], 2), input_partitions=2
     RepartitionExec: partitioning=RoundRobinBatch(2), input_partitions=1
       AggregateExec: mode=Partial, gby=[ip@0 as ip], aggr=[COUNT(Int64(1))]
```

Can anyone explain why the `RepartitionExec: partitioning=RoundRobinBatch(2), input_partitions=1` could accelerate the plan? In my view, removing this `RepartitionExec` will be faster 😂

Thanks in advance.
